--- 
rackup: /srv/code/symbiosis-spanel/config.ru
pid: symbiosis-spanel.pid
group: admin
address: 0.0.0.0
timeout: 30
port: 7962
log: logs/symbiosis-spanel.log
max_conns: 1024
require: []

max_persistent_conns: 512
environment: development
user: admin
servers: 1
daemonize: true
chdir: /srv/code/symbiosis-spanel
